default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "db") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "movie_reservation_system") %>
