default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "movie_reservation_system_development") %>
  host: db
  username: postgres
  password: password
test:
  <<: *default
  database: movie_reservation_system_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  connects_to:
    database:
      writing: production
      reading: production
    cache: cache

cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: solid_cache_production

cable:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "movie_reservation_system_cable") %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV.fetch("DB_NAME", "movie_reservation_system_queue") %>
