#default: &default
#  adapter: postgresql
#  encoding: unicode
#  username: postgres
#  password: mypassword123
#  host: localhost
#  port: 5432


#development:
#  <<: *default
#  database: movie_reservation_system_development

#test:
#  <<: *default
#  database: movie_reservation_system_test

#production:
#  <<: *default
#  database: movie_reservation_system_production
#  username: movie_reservation_system
#  password: <%#= ENV["MOVIE_RESERVATION_SYSTEM_DATABASE_PASSWORD"] %>

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: 5

development:
  <<: *default
  database: movie_reservation_system

test:
  <<: *default
  database: movie_reservation_system_test

production:
  <<: *default
  database: movie_reservation_system_production
  username: movie_reservation_system
  password: <%= ENV["MOVIE_RESERVATION_SYSTEM_DATABASE_PASSWORD"] %>
